-- USING VIEWS

-- CREATE A VIEW

CREATE VIEW EMPSALARY AS SELECT EMP_ID, F_NAME, L_NAME, B_DATE, SEX, SALARY 
FROM EMPLOYEES;

SELECT * FROM EMPSALARY;

-- UPDATE A VIEW

CREATE OR REPLACE VIEW EMPSALARY AS
SELECT EMP_ID, F_NAME, L_NAME, B_DATE, SEX, JOB_TITLE, MIN_SALARY, MAX_SALARY 
FROM EMPLOYEES, JOBS 
WHERE EMPLOYEES.JOB_ID = JOBS.JOB_IDENT;

SELECT * FROM EMPSALARY;

-- DROP A VIEW

DROP VIEW EMPSALARY;

SELECT * FROM EMPSALARY;